version: "3"

services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: ./${INFRA_PATH}/apache/Dockerfile
    ports:
      - ${APP_PORT}:80
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./${APP_PATH}:/var/www/html
      - ./${INFRA_PATH}/apache/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - rust-cms
  db:
    container_name: db
    build:
      context: ./${INFRA_PATH}/db
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./${INFRA_PATH}/db/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      TZ: 'Asia/Tokyo'
    networks:
      - rust-cms

volumes:
  db-store:

networks:
  rust-cms: