version: "3"

services:
  db:
    container_name: postgres
    image: postgres:15
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  db-store:
